# getting start to test
# 1. go run main.go http start
# 2. run each http call you want

### put category
PUT http://localhost:4000/api/categories
Content-Type: application/json

{
  "Category": {
    "Name": "테스트1",
    "Code": "test1",
    "Depth": 1,
    "Sort": 2,
    "Category1ID": "",
    "Category2ID": "",
    "Category3ID": "",
    "Category4ID": ""
  }
}

### get categories
GET http://localhost:4000/api/categories
Content-Type: application/json

### get category
GET http://localhost:4000/api/categories/1d93c7e1-5c77-44b9-b6ab-f192c9ab35a1
Content-Type: application/json



### put manufacture
PUT http://localhost:4000/api/manufactures
Content-Type: application/json

{
  "Manufacture": "test1"
}

### get manufactures
GET http://localhost:4000/api/manufactures
Content-Type: application/json


### get manufactures
GET http://localhost:4000/health


