# getting start to test
# 1. go run main.go http start
# 2. run each http call you want

### put category
PUT http://localhost:4000/api/categories
Content-Type: application/json

{
  "Category": {
    "Name": "테스트2",
    "Code": "test2",
    "Depth": 1,
    "Sort": 2,
    "Category1ID": "",
    "Category2ID": "",
    "Category3ID": "",
    "Category4ID": ""
  }
}

### get categories
GET http://localhost:4000/api/categories
Content-Type: application/json

### get category
GET http://localhost:4000/api/categories/50eda37c-e757-4224-9f22-23acb2c04558
Content-Type: application/json



### put manufacture
PUT http://localhost:4000/api/manufactures
Content-Type: application/json

{
  "Manufacture": {
    "Name": "테스트1",
    "Code": "test1",
    "CompanyRegistrationNumber": "123-123123-123123"
  }
}

### get manufactures
GET http://localhost:4000/api/manufactures
Content-Type: application/json


### get manufactures
GET http://localhost:4000/api/manufactures/208eabd7-0a84-4b4b-9a47-d35fb31f3d99
Content-Type: application/json

