# serverless.yml

# 참고1: https://nextjs.org/blog/next-8#serverless-nextjs

# Lambda Edge를 쓰는데 lambda edge는 runtime 환경변수를 쓰지 못함 그러므로, build time시점의 환경변수 밖에 이용하지 못함.
# serverless.yml을 이용해서 ssm으로 값을 불러서 환경변수 넣는것은 불가능함.
# 이거 ssm 못읽음 component 부터는 못 읽는듯 env만 읽을 수 있음.

J_ENV: ${env.J_ENV}
J_CICD: ${env.J_CICD}
ADMIN_AWS_ACM_ARN: ${env.ADMIN_AWS_ACM_ARN}
ADMIN_AWS_ROLE_ARN: ${env.ADMIN_AWS_ROLE_ARN}

nearsfeed-admin:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    name: nearsfeed-admin
    roleArn: ${ADMIN_AWS_ROLE_ARN}

    bucketName: nearsfeed-admin
    bucketRegion: us-east-1
    build:
      env:
        J_ENV: ${J_ENV}
        J_CICD: ${J_CICD}
    domain: ["admin.alpha", "nearsfeed.com"]
    cloudfront:
      # api/*:
      #   forward:
      #     headers: [Host]
      distributionId: E1W3Y5SGQ2B113
      certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: ${ADMIN_AWS_ACM_ARN}
