frameworkVersion: "2"

plugins:
  - serverless-domain-manager

service: nearsfeed-api
org: nearsfeed

provider:
  name: aws
  runtime: go1.x
  stage: ${env:J_ENV}
  region: ${env:AWS_REGION}
  deploymentBucket: nearsfeed-lambda
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  logs:
    http: true
  environment:
    J_ENV: ${env:J_ENV}
    J_CICD: ${env:J_CICD}

  iam:
    role:
      statements:
        - Effect: "Allow" # VPC 할 때 쓸라고..
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "ec2:CreateNetworkInterface"
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:DeleteNetworkInterface"
            - "ec2:AssignPrivateIpAddresses"
            - "ec2:UnassignPrivateIpAddresses"
          Resource: "*"

        - Effect: "Allow" # APM도구로 x-ray 할 때 쓸라고..
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
            - "xray:GetSamplingRules"
            - "xray:GetSamplingTargets"
            - "xray:GetSamplingStatisticSummaries"
          Resource: "*"

        - Effect: "Allow" # S3에 swagger가져올겸.. 겸사겸사
          Action:
            - "s3:*"
          Resource: "*"

        - Effect: "Allow" # SSM으로 환경변수 불러오는거 관리할라고
          Action:
            - "kms:Decrypt"
            - "kms:Encrypt"
            - "kms:DescribeKey"
            - "ssm:GetParametersByPath"
            - "ssm:GetParameters"
            - "ssm:GetParameter"
          Resource: "*"

package:
  exclude:
    - ./**
  #  exclude:
  #    - serverless.yml
  #    - .idea
  #    - .serverless
  #    - .gitignore
  include:
    - ./bin/**

functions:
  api:
    handler: bin/lambda
    events:
      - http:
          path: /{proxy+}
          method: ANY

custom:
  customDomain:
    domainName: "api.alpha.nearsfeed.com"
    basePath: ""
    hostedZoneId: ${ssm.ap-northeast-2:/nearsfeed/infra/aws_route_53/nearsfeed.com/zone_id~true}
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: ${ssm.ap-northeast-2:/nearsfeed/infra/aws_acm_certificate/nearsfeed.com/domain~true}
